name: flutter_i18n_locize_example
version: 0.0.2
homepage: "https://github.com/defint/flutter_i18n_locize"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: