name: flutter_i18n_locize
description: Easy integration locize.io to flutter_i18n. Contains methods to fetch translations and upload new translations.
version: 0.0.2
homepage: "https://github.com/defint/flutter_i18n_locize"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  dio: "^3.0.0"
  yaml: "^2.2.1"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: