name: flutter_i18n_locize
description: Easy integration locize.io to flutter_i18n. Contains methods to fetch translations and upload new translations.
version: 1.0.0
homepage: "https://github.com/defint/flutter_i18n_locize"

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  dio: ^4.0.0
  yaml: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: